### ISSUE TITLE
`graphql-fetch-cloudflare-auth.ts` 

### ISSUE THREAD

**Issue by elbotho** [serlo/local-dev-env#3]
- currently `jsonwebtoken` is not installed in the frontend so the import fails
- could we the env.local setting in the frontend repo so we don't need to patch this file? (should not be a lot of code right?)

**Comment by hugotiburtino** [comment]
Both would be resolved if we can integrate a local Cloudflare Worker.

> currently jsonwebtoken is not installed in the frontend so the import fails

not really installed, but isn't it installed due to another dependency?

**Comment by elbotho** [comment]
> not really installed, but isn't it installed due to another dependency?

I guess, but TS stops builds anyway.

> Both would be resolved if we can integrate a local Cloudflare Worker.

Closing in favour of #2 then. Thanks!
